export const BOOK_TICKET_REQUEST = 'BOOK_TICKET_REQUEST'
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS'
export const BOOK_TICKET_FAIL = 'BOOK_TICKET_FAIL'

export const GET_TICKET_REQUEST = 'GET_TICKET_REQUEST'
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS'
export const GET_TICKET_FAIL = 'GET_TICKET_FAIL'
