export const EMPLOYEE_CURRENT_LIST_REQUEST = 'EMPLOYEE_CURRENT_LIST_REQUEST'
export const EMPLOYEE_CURRENT_LIST_SUCCESS = 'EMPLOYEE_CURRENT_LIST_SUCCESS'
export const EMPLOYEE_CURRENT_LIST_FAIL = 'EMPLOYEE_CURRENT_LIST_FAIL'
