export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL'

export const MOVIE_CREATE_REVIEW_REQUEST = 'MOVIE_CREATE_REVIEW_REQUEST'
export const MOVIE_CREATE_REVIEW_SUCCESS = 'MOVIE_CREATE_REVIEW_SUCCESS'
export const MOVIE_CREATE_REVIEW_FAIL = 'MOVIE_CREATE_REVIEW_FAIL'
export const MOVIE_CREATE_REVIEW_RESET = 'MOVIE_CREATE_REVIEW_RESET'
