export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST'
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS'
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL'

export const EMPLOYEE_CURRENT_LIST_REQUEST = 'EMPLOYEE_CURRENT_LIST_REQUEST'
export const EMPLOYEE_CURRENT_LIST_SUCCESS = 'EMPLOYEE_CURRENT_LIST_SUCCESS'
export const EMPLOYEE_CURRENT_LIST_FAIL = 'EMPLOYEE_CURRENT_LIST_FAIL'

export const EMPLOYEE_PAST_LIST_REQUEST = 'EMPLOYEE_PAST_LIST_REQUEST'
export const EMPLOYEE_PAST_LIST_SUCCESS = 'EMPLOYEE_PAST_LIST_SUCCESS'
export const EMPLOYEE_PAST_LIST_FAIL = 'EMPLOYEE_PAST_LIST_FAIL'

export const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST'
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS'
export const EMPLOYEE_ADD_FAIL = 'EMPLOYEE_ADD_FAIL'

export const EMPLOYEE_START_WORK_REQUEST = 'EMPLOYEE_START_WORK_REQUEST'
export const EMPLOYEE_START_WORK_SUCCESS = 'EMPLOYEE_START_WORK_SUCCESS'
export const EMPLOYEE_START_WORK_FAIL = 'EMPLOYEE_START_WORK_FAIL'

export const EMPLOYEE_STOP_WORK_REQUEST = 'EMPLOYEE_STOP_WORK_REQUEST'
export const EMPLOYEE_STOP_WORK_SUCCESS = 'EMPLOYEE_STOP_WORK_SUCCESS'
export const EMPLOYEE_STOP_WORK_FAIL = 'EMPLOYEE_STOP_WORK_FAIL'

export const EMPLOYEE_CONTACT_REQUEST = 'EMPLOYEE_CONTACT_REQUEST'
export const EMPLOYEE_CONTACT_SUCCESS = 'EMPLOYEE_CONTACT_SUCCESS'
export const EMPLOYEE_CONTACT_FAIL = 'EMPLOYEE_CONTACT_FAIL'
