export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const MOVIE_CURRENT_LIST_REQUEST = 'MOVIE_CURRENT_LIST_REQUEST'
export const MOVIE_CURRENT_LIST_SUCCESS = 'MOVIE_CURRENT_LIST_SUCCESS'
export const MOVIE_CURRENT_LIST_FAIL = 'MOVIE_CURRENT_LIST_FAIL'

export const MOVIE_PAST_LIST_REQUEST = 'MOVIE_PAST_LIST_REQUEST'
export const MOVIE_PAST_LIST_SUCCESS = 'MOVIE_PAST_LIST_SUCCESS'
export const MOVIE_PAST_LIST_FAIL = 'MOVIE_PAST_LIST_FAIL'

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL'

export const MOVIE_UPDATE_REQUEST = 'MOVIE_UPDATE_REQUEST'
export const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS'
export const MOVIE_UPDATE_FAIL = 'MOVIE_UPDATE_FAIL'

export const MOVIE_START_SCREEN_REQUEST = 'MOVIE_START_SCREEN_REQUEST'
export const MOVIE_START_SCREEN_SUCCESS = 'MOVIE_START_SCREEN_SUCCESS'
export const MOVIE_START_SCREEN_FAIL = 'MOVIE_START_SCREEN_FAIL'

export const MOVIE_STOP_SCREEN_REQUEST = 'MOVIE_STOP_SCREEN_REQUEST'
export const MOVIE_STOP_SCREEN_SUCCESS = 'MOVIE_STOP_SCREEN_SUCCESS'
export const MOVIE_STOP_SCREEN_FAIL = 'MOVIE_STOP_SCREEN_FAIL'

export const MOVIE_ADD_REQUEST = 'MOVIE_ADD_REQUEST'
export const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS'
export const MOVIE_ADD_FAIL = 'MOVIE_ADD_FAIL'

export const MOVIE_PROFITS_REQUEST = 'MOVIE_PROFITS_REQUEST'
export const MOVIE_PROFITS_SUCCESS = 'MOVIE_PROFITS_SUCCESS'
export const MOVIE_PROFITS_FAIL = 'MOVIE_PROFITS_FAIL'

export const MOVIE_GENRE_PROFITS_REQUEST = 'MOVIE_GENRE_PROFITS_REQUEST'
export const MOVIE_GENRE_PROFITS_SUCCESS = 'MOVIE_GENRE_PROFITS_SUCCESS'
export const MOVIE_GENRE_PROFITS_FAIL = 'MOVIE_GENRE_PROFITS_FAIL'
