export const REFRESHMENT_LIST_REQUEST = 'REFRESHMENT_LIST_REQUEST'
export const REFRESHMENT_LIST_SUCCESS = 'REFRESHMENT_LIST_SUCCESS'
export const REFRESHMENT_LIST_FAIL = 'REFRESHMENT_LIST_FAIL'

export const REFRESHMENT_DETAILS_REQUEST = 'REFRESHMENT_DETAILS_REQUEST'
export const REFRESHMENT_DETAILS_SUCCESS = 'REFRESHMENT_DETAILS_SUCCESS'
export const REFRESHMENT_DETAILS_FAIL = 'REFRESHMENT_DETAILS_FAIL'

export const REFRESHMENT_UPDATE_REQUEST = 'REFRESHMENT_UPDATE_REQUEST'
export const REFRESHMENT_UPDATE_SUCCESS = 'REFRESHMENT_UPDATE_SUCCESS'
export const REFRESHMENT_UPDATE_FAIL = 'REFRESHMENT_UPDATE_FAIL'

export const REFRESHMENT_DELETE_REQUEST = 'REFRESHMENT_DELETE_REQUEST'
export const REFRESHMENT_DELETE_SUCCESS = 'REFRESHMENT_DELETE_SUCCESS'
export const REFRESHMENT_DELETE_FAIL = 'REFRESHMENT_DELETE_FAIL'

export const REFRESHMENT_ADD_REQUEST = 'REFRESHMENT_ADD_REQUEST'
export const REFRESHMENT_ADD_SUCCESS = 'REFRESHMENT_ADD_SUCCESS'
export const REFRESHMENT_ADD_FAIL = 'REFRESHMENT_ADD_FAIL'
