export const SHOW_CREATE_REQUEST = 'SHOW_CREATE_REQUEST'
export const SHOW_CREATE_SUCCESS = 'SHOW_CREATE_SUCCESS'
export const SHOW_CREATE_FAIL = 'SHOW_CREATE_FAIL'

export const SHOW_DETAILS_REQUEST = 'SHOW_DETAILS_REQUEST'
export const SHOW_DETAILS_SUCCESS = 'SHOW_DETAILS_SUCCESS'
export const SHOW_DETAILS_FAIL = 'SHOW_DETAILS_FAIL'

export const SHOW_LIST_REQUEST = 'SHOW_LIST_REQUEST'
export const SHOW_LIST_SUCCESS = 'SHOW_LIST_SUCCESS'
export const SHOW_LIST_FAIL = 'SHOW_LIST_FAIL'

export const SHOW_FUTURE_LIST_REQUEST = 'SHOW_FUTURE_LIST_REQUEST'
export const SHOW_FUTURE_LIST_SUCCESS = 'SHOW_FUTURE_LIST_SUCCESS'
export const SHOW_FUTURE_LIST_FAIL = 'SHOW_FUTURE_LIST_FAIL'

export const SHOW_PAST_LIST_REQUEST = 'SHOW_PAST_LIST_REQUEST'
export const SHOW_PAST_LIST_SUCCESS = 'SHOW_PAST_LIST_SUCCESS'
export const SHOW_PAST_LIST_FAIL = 'SHOW_PAST_LIST_FAIL'

export const SHOW_UPDATE_REQUEST = 'SHOW_UPDATE_REQUEST'
export const SHOW_UPDATE_SUCCESS = 'SHOW_UPDATE_SUCCESS'
export const SHOW_UPDATE_FAIL = 'SHOW_UPDATE_FAIL'

export const SHOW_MARK_REQUEST = 'SHOW_MARK_REQUEST'
export const SHOW_MARK_SUCCESS = 'SHOW_MARK_SUCCESS'
export const SHOW_MARK_FAIL = 'SHOW_MARK_FAIL'
